export const PATHS = {
  EVENTS: 'events',
  ADDEVENT: 'add-event',
  EDITEVENT: 'edit-event',
  ADMIN: 'admin',
  BUYTICKET: 'buy-ticket',
  EDITPROFILE: 'edit-profile',
  EVENT: 'event',
  LOGIN: 'login',
  PROFILE: 'profile',
  PROMOCODE: 'promo-code',
  PROMOCODEDETAILS: 'promo-code-details',
  REGISTER: 'register',
  VERIFYACCOUNT: 'verify',
  RESETPASSWORD: 'reset-password',
  EMAILFORRESET: 'enter-email',
  EVENTLIST: 'event-list',
  EVENTDETAILSADMIN: 'event-details',
  CHECKOUT: 'checkout',
  PAYMENT: 'payment',
  PAYMENTCANCEL: 'payment-cancel',
  PAYMENTSUCCESS: 'payment-success',
  SCAN: 'scan',
};
