export const PATHS = {
  EVENTS: 'events',
  ADDEVENT: 'add-event',
  EDITEVENT: 'edit-event',
  ADMIN: 'admin',
  BUYTICKET: 'buy-ticket',
  EDITPROFIL: 'edit-profil',
  EVENT: 'event',
  LOGIN: 'login',
  PROFIL: 'profil',
  PROMOCODE: 'promo-code',
  PROMOCODEDETAILS: 'promo-code-details',
  REGISTER: 'register',
  SCANTICKETS: 'scan-tickets',
};
