export const PATHS = {
  EVENTS: 'events',
  ADDEVENT: 'add-event',
  EDITEVENT: 'edit-event',
  ADMIN: 'admin',
  BUYTICKET: 'buy-ticket',
  EDITPROFILE: 'edit-profile',
  EVENT: 'event',
  LOGIN: 'login',
  PROFILE: 'profile',
  PROMOCODE: 'promo-code',
  PROMOCODEDETAILS: 'promo-code-details',
  REGISTER: 'register',
  SCANTICKETS: 'scan-tickets',
  FORGOTPASSWORD: 'forgot-password',
};
